In [11]:
import numpy as np
from scipy.stats import spearmanr

# Generate example similarity matrices (100x100)
cosine_matrix1 = np.random.rand(100, 100)
cosine_matrix2 = np.random.rand(100, 100)

# Initialize a list to store Spearman correlation coefficients for each row
spearman_correlations = []

# Loop over each row
for i in range(100):
    # Get the indices of the top 10 values in the row for both matrices
    top10_indices_1 = np.argsort(cosine_matrix1[i])[-10:]
    top10_indices_2 = np.argsort(cosine_matrix2[i])[-10:]
    
    # Create a combined list of top indices
    combined_indices = np.union1d(top10_indices_1, top10_indices_2)
    
    # Create rank vectors for the combined indices
    rank_vector1 = np.argsort(np.argsort(cosine_matrix1[i][combined_indices]))
    rank_vector2 = np.argsort(np.argsort(cosine_matrix2[i][combined_indices]))
    
    # Calculate Spearman's rank correlation coefficient for the combined top 10 items
    spearman_corr, _ = spearmanr(rank_vector1, rank_vector2)
    
    # Append the result to the list
    spearman_correlations.append(spearman_corr)

# Convert list to numpy array for better analysis
spearman_correlations = np.array(spearman_correlations)

print(f"Spearman rank correlations for each row's top 10 items: {spearman_correlations}")
print(f"Mean Spearman rank correlation: {np.mean(spearman_correlations)}")
print(f"Standard Deviation of Spearman rank correlations: {np.std(spearman_correlations)}")

Spearman rank correlations for each row's top 10 items: [-0.71879699 -0.74210526 -0.47574819 -0.81578947 -0.61578947 -0.30147059
 -0.75263158 -0.83007519 -0.71879699 -0.61929825 -0.76992481 -0.81654135
 -0.88721805 -0.76666667 -0.49264706 -0.78070175 -0.65737874 -0.36519608
 -0.60526316 -0.73333333 -0.76992481 -0.5        -0.03921569 -0.67894737
 -0.74736842 -0.54411765 -0.63970588 -0.67368421 -0.8245614  -0.59824561
 -0.78596491 -0.72136223 -0.46130031 -0.83458647 -0.52982456 -0.65263158
 -0.74736842 -0.82406015 -0.76842105 -0.72807018 -0.51960784 -0.70278638
 -0.70701754 -0.67894737 -0.76842105 -0.68070175 -0.76057792 -0.80701754
 -0.56862745 -0.60577915 -0.68596491 -0.81754386 -0.58926729 -0.45614035
 -0.6962406  -0.73157895 -0.750258   -0.59824561 -0.76240602 -0.28173375
 -0.70175439 -0.62229102 -0.63333333 -0.83609023 -0.69298246 -0.64561404
 -0.72781955 -0.74406605 -0.65964912 -0.54210526 -0.7924812  -0.71403509
 -0.57894737 -0.69298246 -0.59803922 -0.8121775  -0.74586466 -0.7254

In [ ]:
models = ["PT SecBert", "FT SecBert", "PT SecureBert",  "FT SecureBert", "PT Gpt2" ,  "FT Gpt2"]
models = ["pretrained_SecBert", "SecBert", "pretrained_SecureBert",  "SecureBert", "pretrained_Gpt2","Gpt2"]


In [4]:
ranks1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
ranks2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
top10_indices_1

array([88, 96, 71, 24, 20, 98, 58, 61, 70, 79])

In [7]:
top10_indices_2

array([78, 83, 37, 75,  3, 45, 14, 65, 64, 55])

In [9]:
cosine_matrix1[i][top10_indices_1]

array([0.83106881, 0.83876092, 0.88062472, 0.8965506 , 0.928922  ,
       0.92894408, 0.93150184, 0.9647035 , 0.96520358, 0.97207685])

In [10]:
cosine_matrix2[i][top10_indices_2]

array([0.93618613, 0.93847017, 0.95409846, 0.95941094, 0.96753227,
       0.97629745, 0.97634475, 0.98347607, 0.99311391, 0.99775101])

In [7]:
import numpy as np
from scipy.stats import spearmanr

# Define the cosine similarity matrices
cosine_matrix1 = np.array([
    [1, 0.9, 0.8, 0.7, 0.6],
    [0.9, 1, 0.9, 0.8, 0.7],
    [0.8, 0.9, 1, 0.9, 0.8],
    [0.7, 0.8, 0.9, 1, 0.9],
    [0.6, 0.7, 0.8, 0.9, 1]
])

cosine_matrix2 = np.array([
    [1, 0.6, 0.7, 0.8, 0.9],
    [0.6, 1, 0.7, 0.8, 0.9],
    [0.7, 0.6, 1, 0.8, 0.9],
    [0.8, 0.7, 0.6, 1, 0.9],
    [0.9, 0.8, 0.7, 0.6, 1]
])

# Initialize a list to store Spearman correlation coefficients for each row
spearman_correlations = []

# Loop over each row
for i in range(1):
    # Get the indices of the top 3 values in the row for both matrices
    top3_indices_1 = np.argsort(cosine_matrix1[i])
    top3_indices_2 = np.argsort(cosine_matrix2[i])
    print(top3_indices_1)
    print(top3_indices_2)
    # Rank the indices within the top 3 values
    ranks1 = np.argsort(np.argsort(cosine_matrix1[i][top3_indices_1]))
    ranks2 = np.argsort(np.argsort(cosine_matrix2[i][top3_indices_2]))
    print(ranks1)
    print(ranks2)
    # Calculate Spearman's rank correlation coefficient for the top 3 items
    spearman_corr, _ = spearmanr(ranks1, ranks2)
    
    # Append the result to the list
    spearman_correlations.append(spearman_corr)

# Convert list to numpy array for better analysis
spearman_correlations = np.array(spearman_correlations)

print(f"Spearman rank correlations for each row's top 3 items: {spearman_correlations}")
print(f"Mean Spearman rank correlation: {np.mean(spearman_correlations)}")
print(f"Standard Deviation of Spearman rank correlations: {np.std(spearman_correlations)}")

[4 3 2 1 0]
[1 2 3 4 0]
[0 1 2 3 4]
[0 1 2 3 4]
Spearman rank correlations for each row's top 3 items: [1.]
Mean Spearman rank correlation: 0.9999999999999999
Standard Deviation of Spearman rank correlations: 0.0


In [6]:
import numpy as np

# Define the cosine similarity matrices
cosine_matrix1 = np.array([
    [1, 0.9, 0.8, 0.7, 0.6],
    [0.9, 1, 0.9, 0.8, 0.7],
    [0.8, 0.9, 1, 0.9, 0.8],
    [0.7, 0.8, 0.9, 1, 0.9],
    [0.6, 0.7, 0.8, 0.9, 1]
])

cosine_matrix2 = np.array([
    [1, 0.6, 0.7, 0.8, 0.9],
    [0.6, 1, 0.7, 0.8, 0.9],
    [0.7, 0.6, 1, 0.8, 0.9],
    [0.8, 0.7, 0.6, 1, 0.9],
    [0.9, 0.8, 0.7, 0.6, 1]
])

# Number of top items to compare
top_n = 3

# Initialize a list to store whether the top N indices match for each row
top_n_match = []

# Loop over each row
for i in range(1):
    # Get the indices of the top N values in the row for both matrices
    top_indices_1 = np.argsort(cosine_matrix1[i])[-top_n:]
    top_indices_2 = np.argsort(cosine_matrix2[i])[-top_n:]
    print(top_indices_1)
    print(top_indices_2)
    # Check if the top indices are the same (regardless of order)
    match = np.array_equal(np.sort(top_indices_1), np.sort(top_indices_2))
    
    # Append the result to the list
    top_n_match.append(match)

print(f"Top {top_n} indices match for each row: {top_n_match}")
print(f"Overall match rate: {np.mean(top_n_match) * 100}%")

[2 1 0]
[3 4 0]
Top 3 indices match for each row: [False]
Overall match rate: 0.0%


In [9]:
import numpy as np

# Define the cosine similarity matrices
cosine_matrix1 = np.array([
    [1, 0.9, 0.8, 0.7, 0.6],
    [0.9, 1, 0.9, 0.8, 0.7],
    [0.8, 0.9, 1, 0.9, 0.8],
    [0.7, 0.8, 0.9, 1, 0.9],
    [0.6, 0.7, 0.8, 0.9, 1]
])

cosine_matrix2 = np.array([
    [1, 0.6, 0.7, 0.8, 0.9],
    [0.6, 1, 0.7, 0.8, 0.9],
    [0.7, 0.6, 1, 0.8, 0.9],
    [0.8, 0.7, 0.6, 1, 0.9],
    [0.9, 0.8, 0.7, 0.6, 1]
])

# Number of top items to compare
top_k = 3

# Initialize a list to store hit@k values for each row
hit_at_k = []

# Loop over each row
for i in range(5):
    # Get the indices of the top k values in the row for both matrices
    top_k_indices_1 = np.argsort(cosine_matrix1[i])[-top_k:]
    top_k_indices_2 = np.argsort(cosine_matrix2[i])[-top_k:]
    print("row: ", i)
    print(top_k_indices_1)
    print(top_k_indices_2)
    
    # Calculate the hit@k (number of common indices in top k)
    hit_count = len(set(top_k_indices_1) & set(top_k_indices_2))
    
    # Append the result to the list
    hit_at_k.append(hit_count)

print(f"Hit@{top_k} for each row: {hit_at_k}")
print(f"Average Hit@{top_k}: {np.mean(hit_at_k)}")

row:  0
[2 1 0]
[3 4 0]
row:  1
[0 2 1]
[3 4 1]
row:  2
[1 3 2]
[3 4 2]
row:  3
[2 4 3]
[0 4 3]
row:  4
[2 3 4]
[1 0 4]
Hit@3 for each row: [1, 1, 2, 2, 1]
Average Hit@3: 1.4
